# Generated by Django 4.0.3 on 2022-09-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Поступил заказ', 'Поступил заказ'), ('Готовится', 'Готовится'), ('Приготовлено', 'Приготовлено'), ('Заказ отдан', 'Заказ отдан')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=250)),
                ('food_count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='main.client')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Поступил заказ', 'Поступил заказ'), ('Готовится', 'Готовится'), ('Приготовлено', 'Приготовлено'), ('Заказ отдан', 'Заказ отдан')], max_length=200, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to='main.admin')),
                ('ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_id', to='main.order')),
            ],
        ),
    ]
